# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c820eb9dfada4216e5b8e64bed63071b5c8625c26b3b9d4b072c789f51bb5b74e5474efb9923d69e1f9b6da91a7226b89fedaf0608af11c57e6d110ccdc03c66

test:
  secret_key_base: 9791b10b53133253939f3d03d271881504ecc114544c5a80384b4b8b81914c07f0710a35dd466c647e76f406d823b5f85fc90233d3a77276c746f97d7e0fb030

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
